ali_source 'alibaba-specs'
ali_source 'alibaba-specs-mirror'
#inhibit_all_warnings!

def common
    pod 'WeexSDK'
    pod 'WXDevtool', '0.9.5'
    pod 'SDWebImage', '3.7.5'
    pod 'SocketRocket', '0.4.2'
    pod 'ATSDK-Weex', '0.0.1'
    pod 'WeexPlguinDemo', :path=>'../../'
    pod 'WeexPluginLoader'
end

target 'WeexDemo' do
    common
end
